/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lclsqeorjabtiplvcsoq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjbHNxZW9yamFidGlwbHZjc29xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwNzU5NzcsImV4cCI6MjA4ODY1MTk3N30.NCWjm6W70sMy1GX_7ZkXt352kikG4WFz8--6GivP4gE"